extends Node

enum GAME_STATES {INITIAL, PLACING_TERRITORIES, ATTACKING, MOVING_TERRITORIES}
enum PLAYER_STATE {PLAYER, IA, DISABLED}

var PLAYER_COUNT = 2

var WINNER = "JOGADOR AZUL"
var WINNER_COLOR = "#009fff"
